/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const InvoiceStatus = IDL.Variant({
  'saved' : IDL.Null,
  'draft' : IDL.Null,
});
export const Address = IDL.Record({
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'email' : IDL.Text,
  'state' : IDL.Text,
  'phone' : IDL.Text,
});
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'billingAddress' : Address,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'gstin' : IDL.Text,
  'shippingAddress' : Address,
  'phone' : IDL.Text,
});
export const InventoryItem = IDL.Record({
  'id' : IDL.Nat,
  'colorCode' : IDL.Text,
  'colorName' : IDL.Text,
  'lowStockThreshold' : IDL.Int,
  'sheetsAvailable' : IDL.Int,
  'thickness' : IDL.Float64,
  'sqftPerSheet' : IDL.Float64,
  'grade' : IDL.Text,
  'length' : IDL.Float64,
  'batchNumber' : IDL.Text,
  'brand' : IDL.Text,
  'width' : IDL.Float64,
});
export const InvoiceType = IDL.Variant({
  'packingList' : IDL.Null,
  'taxInvoice' : IDL.Null,
});
export const InvoiceItem = IDL.Record({
  'qty' : IDL.Float64,
  'colorCode' : IDL.Text,
  'colorName' : IDL.Text,
  'sqft' : IDL.Float64,
  'thickness' : IDL.Float64,
  'grade' : IDL.Text,
  'length' : IDL.Float64,
  'batchNumber' : IDL.Text,
  'brand' : IDL.Text,
  'inventoryId' : IDL.Opt(IDL.Nat),
  'width' : IDL.Float64,
  'lineId' : IDL.Nat,
});
export const Invoice = IDL.Record({
  'id' : IDL.Nat,
  'status' : InvoiceStatus,
  'deliveryAddress' : Address,
  'destination' : IDL.Text,
  'hsnSac' : IDL.Text,
  'taxableAmount' : IDL.Float64,
  'ackDate' : IDL.Text,
  'billingAddress' : Address,
  'city' : IDL.Text,
  'ackNumber' : IDL.Text,
  'lrNo' : IDL.Text,
  'igstAmount' : IDL.Float64,
  'ewayBillNo' : IDL.Text,
  'deliveryMode' : IDL.Text,
  'totalSqft' : IDL.Float64,
  'salesPerson' : IDL.Text,
  'totalQty' : IDL.Float64,
  'grandTotal' : IDL.Float64,
  'invoiceDate' : IDL.Text,
  'invoiceType' : InvoiceType,
  'gstin' : IDL.Text,
  'ratePerSqft' : IDL.Float64,
  'billNumber' : IDL.Text,
  'irnNumber' : IDL.Text,
  'customerId' : IDL.Nat,
  'gstRate' : IDL.Float64,
  'partyName' : IDL.Text,
  'phone' : IDL.Text,
  'items' : IDL.Vec(InvoiceItem),
  'cgstAmount' : IDL.Float64,
  'sgstAmount' : IDL.Float64,
  'remarks' : IDL.Text,
  'piNumber' : IDL.Text,
  'vehicleNo' : IDL.Text,
  'amountInWords' : IDL.Text,
  'dispatchLocation' : IDL.Text,
  'lrDate' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CompanySettings = IDL.Record({
  'email' : IDL.Text,
  'bankName' : IDL.Text,
  'termsAndConditions' : IDL.Text,
  'branchAndIfsc' : IDL.Text,
  'gstin' : IDL.Text,
  'address' : Address,
  'companyName' : IDL.Text,
  'accountNumber' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changeInvoiceStatus' : IDL.Func([IDL.Nat, InvoiceStatus], [], []),
  'createCustomer' : IDL.Func([Customer], [IDL.Nat], []),
  'createInventoryItem' : IDL.Func([InventoryItem], [IDL.Nat], []),
  'createInvoice' : IDL.Func([Invoice], [IDL.Nat], []),
  'deductStock' : IDL.Func([IDL.Nat, IDL.Int], [], []),
  'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
  'deleteInventoryItem' : IDL.Func([IDL.Nat], [], []),
  'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompanySettings' : IDL.Func([], [IDL.Opt(CompanySettings)], ['query']),
  'getCustomer' : IDL.Func([IDL.Nat], [Customer], ['query']),
  'getCustomerPurchaseHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'invoiceCount' : IDL.Nat, 'totalSqft' : IDL.Float64 })],
      ['query'],
    ),
  'getInventoryItem' : IDL.Func([IDL.Nat], [InventoryItem], ['query']),
  'getInvoice' : IDL.Func([IDL.Nat], [Invoice], ['query']),
  'getLowStockItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getSalesSummary' : IDL.Func(
      [],
      [IDL.Record({ 'totalSqft' : IDL.Float64, 'totalInvoices' : IDL.Nat })],
      ['query'],
    ),
  'getStockReport' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'listInventory' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'listInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCompanySettings' : IDL.Func([CompanySettings], [], []),
  'updateCustomer' : IDL.Func([Customer], [], []),
  'updateInventoryItem' : IDL.Func([InventoryItem], [], []),
  'updateInvoice' : IDL.Func([Invoice], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const InvoiceStatus = IDL.Variant({ 'saved' : IDL.Null, 'draft' : IDL.Null });
  const Address = IDL.Record({
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'email' : IDL.Text,
    'state' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'billingAddress' : Address,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'gstin' : IDL.Text,
    'shippingAddress' : Address,
    'phone' : IDL.Text,
  });
  const InventoryItem = IDL.Record({
    'id' : IDL.Nat,
    'colorCode' : IDL.Text,
    'colorName' : IDL.Text,
    'lowStockThreshold' : IDL.Int,
    'sheetsAvailable' : IDL.Int,
    'thickness' : IDL.Float64,
    'sqftPerSheet' : IDL.Float64,
    'grade' : IDL.Text,
    'length' : IDL.Float64,
    'batchNumber' : IDL.Text,
    'brand' : IDL.Text,
    'width' : IDL.Float64,
  });
  const InvoiceType = IDL.Variant({
    'packingList' : IDL.Null,
    'taxInvoice' : IDL.Null,
  });
  const InvoiceItem = IDL.Record({
    'qty' : IDL.Float64,
    'colorCode' : IDL.Text,
    'colorName' : IDL.Text,
    'sqft' : IDL.Float64,
    'thickness' : IDL.Float64,
    'grade' : IDL.Text,
    'length' : IDL.Float64,
    'batchNumber' : IDL.Text,
    'brand' : IDL.Text,
    'inventoryId' : IDL.Opt(IDL.Nat),
    'width' : IDL.Float64,
    'lineId' : IDL.Nat,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Nat,
    'status' : InvoiceStatus,
    'deliveryAddress' : Address,
    'destination' : IDL.Text,
    'hsnSac' : IDL.Text,
    'taxableAmount' : IDL.Float64,
    'ackDate' : IDL.Text,
    'billingAddress' : Address,
    'city' : IDL.Text,
    'ackNumber' : IDL.Text,
    'lrNo' : IDL.Text,
    'igstAmount' : IDL.Float64,
    'ewayBillNo' : IDL.Text,
    'deliveryMode' : IDL.Text,
    'totalSqft' : IDL.Float64,
    'salesPerson' : IDL.Text,
    'totalQty' : IDL.Float64,
    'grandTotal' : IDL.Float64,
    'invoiceDate' : IDL.Text,
    'invoiceType' : InvoiceType,
    'gstin' : IDL.Text,
    'ratePerSqft' : IDL.Float64,
    'billNumber' : IDL.Text,
    'irnNumber' : IDL.Text,
    'customerId' : IDL.Nat,
    'gstRate' : IDL.Float64,
    'partyName' : IDL.Text,
    'phone' : IDL.Text,
    'items' : IDL.Vec(InvoiceItem),
    'cgstAmount' : IDL.Float64,
    'sgstAmount' : IDL.Float64,
    'remarks' : IDL.Text,
    'piNumber' : IDL.Text,
    'vehicleNo' : IDL.Text,
    'amountInWords' : IDL.Text,
    'dispatchLocation' : IDL.Text,
    'lrDate' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CompanySettings = IDL.Record({
    'email' : IDL.Text,
    'bankName' : IDL.Text,
    'termsAndConditions' : IDL.Text,
    'branchAndIfsc' : IDL.Text,
    'gstin' : IDL.Text,
    'address' : Address,
    'companyName' : IDL.Text,
    'accountNumber' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changeInvoiceStatus' : IDL.Func([IDL.Nat, InvoiceStatus], [], []),
    'createCustomer' : IDL.Func([Customer], [IDL.Nat], []),
    'createInventoryItem' : IDL.Func([InventoryItem], [IDL.Nat], []),
    'createInvoice' : IDL.Func([Invoice], [IDL.Nat], []),
    'deductStock' : IDL.Func([IDL.Nat, IDL.Int], [], []),
    'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
    'deleteInventoryItem' : IDL.Func([IDL.Nat], [], []),
    'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompanySettings' : IDL.Func([], [IDL.Opt(CompanySettings)], ['query']),
    'getCustomer' : IDL.Func([IDL.Nat], [Customer], ['query']),
    'getCustomerPurchaseHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Record({ 'invoiceCount' : IDL.Nat, 'totalSqft' : IDL.Float64 })],
        ['query'],
      ),
    'getInventoryItem' : IDL.Func([IDL.Nat], [InventoryItem], ['query']),
    'getInvoice' : IDL.Func([IDL.Nat], [Invoice], ['query']),
    'getLowStockItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getSalesSummary' : IDL.Func(
        [],
        [IDL.Record({ 'totalSqft' : IDL.Float64, 'totalInvoices' : IDL.Nat })],
        ['query'],
      ),
    'getStockReport' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'listInventory' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'listInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCompanySettings' : IDL.Func([CompanySettings], [], []),
    'updateCustomer' : IDL.Func([Customer], [], []),
    'updateInventoryItem' : IDL.Func([InventoryItem], [], []),
    'updateInvoice' : IDL.Func([Invoice], [], []),
  });
};

export const init = ({ IDL }) => { return []; };