/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'street' : string,
  'country' : string,
  'city' : string,
  'email' : string,
  'state' : string,
  'phone' : string,
}
export interface CompanySettings {
  'email' : string,
  'bankName' : string,
  'termsAndConditions' : string,
  'branchAndIfsc' : string,
  'gstin' : string,
  'address' : Address,
  'companyName' : string,
  'accountNumber' : string,
  'phone' : string,
}
export interface Customer {
  'id' : bigint,
  'billingAddress' : Address,
  'name' : string,
  'email' : string,
  'gstin' : string,
  'shippingAddress' : Address,
  'phone' : string,
}
export interface CustomerPricing {
  'id' : bigint,
  'note' : string,
  'customRate' : number,
  'customerId' : bigint,
  'inventoryId' : bigint,
}
export interface InventoryItem {
  'id' : bigint,
  'colorCode' : string,
  'colorName' : string,
  'lowStockThreshold' : bigint,
  'purchaseRate' : number,
  'sheetsAvailable' : bigint,
  'thickness' : number,
  'sellingRate' : number,
  'sqftPerSheet' : number,
  'grade' : string,
  'length' : number,
  'batchNumber' : string,
  'brand' : string,
  'width' : number,
}
export interface Invoice {
  'id' : bigint,
  'status' : InvoiceStatus,
  'deliveryAddress' : Address,
  'destination' : string,
  'hsnSac' : string,
  'taxableAmount' : number,
  'ackDate' : string,
  'billingAddress' : Address,
  'city' : string,
  'ackNumber' : string,
  'lrNo' : string,
  'igstAmount' : number,
  'ewayBillNo' : string,
  'deliveryMode' : string,
  'totalSqft' : number,
  'salesPerson' : string,
  'totalQty' : number,
  'grandTotal' : number,
  'invoiceDate' : string,
  'invoiceType' : InvoiceType,
  'gstin' : string,
  'ratePerSqft' : number,
  'billNumber' : string,
  'irnNumber' : string,
  'customerId' : bigint,
  'gstRate' : number,
  'partyName' : string,
  'phone' : string,
  'items' : Array<InvoiceItem>,
  'cgstAmount' : number,
  'sgstAmount' : number,
  'remarks' : string,
  'piNumber' : string,
  'vehicleNo' : string,
  'amountInWords' : string,
  'dispatchLocation' : string,
  'lrDate' : string,
}
export interface InvoiceItem {
  'qty' : number,
  'colorCode' : string,
  'colorName' : string,
  'sqft' : number,
  'thickness' : number,
  'grade' : string,
  'length' : number,
  'batchNumber' : string,
  'brand' : string,
  'inventoryId' : [] | [bigint],
  'width' : number,
  'lineId' : bigint,
}
export type InvoiceStatus = { 'saved' : null } |
  { 'draft' : null };
export type InvoiceType = { 'packingList' : null } |
  { 'taxInvoice' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changeInvoiceStatus' : ActorMethod<[bigint, InvoiceStatus], undefined>,
  'createCustomer' : ActorMethod<[Customer], bigint>,
  'createInventoryItem' : ActorMethod<[InventoryItem], bigint>,
  'createInvoice' : ActorMethod<[Invoice], bigint>,
  'deductStock' : ActorMethod<[bigint, bigint], undefined>,
  'deleteCustomer' : ActorMethod<[bigint], undefined>,
  'deleteCustomerPricing' : ActorMethod<[bigint], undefined>,
  'deleteInventoryItem' : ActorMethod<[bigint], undefined>,
  'deleteInvoice' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompanySettings' : ActorMethod<[], [] | [CompanySettings]>,
  'getCustomer' : ActorMethod<[bigint], Customer>,
  'getCustomerPricingByCustomerAndItem' : ActorMethod<
    [bigint, bigint],
    [] | [CustomerPricing]
  >,
  'getCustomerPurchaseHistory' : ActorMethod<
    [bigint],
    { 'invoiceCount' : bigint, 'totalSqft' : number }
  >,
  'getInventoryItem' : ActorMethod<[bigint], InventoryItem>,
  'getInvoice' : ActorMethod<[bigint], Invoice>,
  'getLowStockItems' : ActorMethod<[], Array<InventoryItem>>,
  'getSalesSummary' : ActorMethod<
    [],
    { 'totalSqft' : number, 'totalInvoices' : bigint }
  >,
  'getStockReport' : ActorMethod<[], Array<InventoryItem>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllCustomerPricings' : ActorMethod<[], Array<CustomerPricing>>,
  'listCustomerPricingsByCustomer' : ActorMethod<
    [bigint],
    Array<CustomerPricing>
  >,
  'listCustomers' : ActorMethod<[], Array<Customer>>,
  'listInventory' : ActorMethod<[], Array<InventoryItem>>,
  'listInvoices' : ActorMethod<[], Array<Invoice>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCustomerPricing' : ActorMethod<[CustomerPricing], bigint>,
  'updateCompanySettings' : ActorMethod<[CompanySettings], undefined>,
  'updateCustomer' : ActorMethod<[Customer], undefined>,
  'updateInventoryItem' : ActorMethod<[InventoryItem], undefined>,
  'updateInvoice' : ActorMethod<[Invoice], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];