/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface InventoryItem {
    id: bigint;
    colorCode: string;
    colorName: string;
    lowStockThreshold: bigint;
    sheetsAvailable: bigint;
    thickness: number;
    sqftPerSheet: number;
    grade: string;
    length: number;
    batchNumber: string;
    brand: string;
    width: number;
}
export interface InvoiceItem {
    qty: number;
    colorCode: string;
    colorName: string;
    sqft: number;
    thickness: number;
    grade: string;
    length: number;
    batchNumber: string;
    brand: string;
    inventoryId?: bigint;
    width: number;
    lineId: bigint;
}
export interface CompanySettings {
    email: string;
    bankName: string;
    termsAndConditions: string;
    branchAndIfsc: string;
    gstin: string;
    address: Address;
    companyName: string;
    accountNumber: string;
    phone: string;
}
export interface Invoice {
    id: bigint;
    status: InvoiceStatus;
    deliveryAddress: Address;
    destination: string;
    hsnSac: string;
    taxableAmount: number;
    ackDate: string;
    billingAddress: Address;
    city: string;
    ackNumber: string;
    lrNo: string;
    igstAmount: number;
    ewayBillNo: string;
    deliveryMode: string;
    totalSqft: number;
    salesPerson: string;
    totalQty: number;
    grandTotal: number;
    invoiceDate: string;
    invoiceType: InvoiceType;
    gstin: string;
    ratePerSqft: number;
    billNumber: string;
    irnNumber: string;
    customerId: bigint;
    gstRate: number;
    partyName: string;
    phone: string;
    items: Array<InvoiceItem>;
    cgstAmount: number;
    sgstAmount: number;
    remarks: string;
    piNumber: string;
    vehicleNo: string;
    amountInWords: string;
    dispatchLocation: string;
    lrDate: string;
}
export interface Customer {
    id: bigint;
    billingAddress: Address;
    name: string;
    email: string;
    gstin: string;
    shippingAddress: Address;
    phone: string;
}
export interface UserProfile {
    name: string;
}
export interface Address {
    street: string;
    country: string;
    city: string;
    email: string;
    state: string;
    phone: string;
}
export enum InvoiceStatus {
    saved = "saved",
    draft = "draft"
}
export enum InvoiceType {
    packingList = "packingList",
    taxInvoice = "taxInvoice"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    changeInvoiceStatus(id: bigint, status: InvoiceStatus): Promise<void>;
    createCustomer(customer: Customer): Promise<bigint>;
    createInventoryItem(item: InventoryItem): Promise<bigint>;
    createInvoice(invoice: Invoice): Promise<bigint>;
    deductStock(id: bigint, qty: bigint): Promise<void>;
    deleteCustomer(id: bigint): Promise<void>;
    deleteInventoryItem(id: bigint): Promise<void>;
    deleteInvoice(id: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCompanySettings(): Promise<CompanySettings | null>;
    getCustomer(id: bigint): Promise<Customer>;
    getCustomerPurchaseHistory(customerId: bigint): Promise<{
        invoiceCount: bigint;
        totalSqft: number;
    }>;
    getInventoryItem(id: bigint): Promise<InventoryItem>;
    getInvoice(id: bigint): Promise<Invoice>;
    getLowStockItems(): Promise<Array<InventoryItem>>;
    getSalesSummary(): Promise<{
        totalSqft: number;
        totalInvoices: bigint;
    }>;
    getStockReport(): Promise<Array<InventoryItem>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listCustomers(): Promise<Array<Customer>>;
    listInventory(): Promise<Array<InventoryItem>>;
    listInvoices(): Promise<Array<Invoice>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateCompanySettings(settings: CompanySettings): Promise<void>;
    updateCustomer(customer: Customer): Promise<void>;
    updateInventoryItem(item: InventoryItem): Promise<void>;
    updateInvoice(invoice: Invoice): Promise<void>;
}
import type { Address as _Address, CompanySettings as _CompanySettings, Invoice as _Invoice, InvoiceItem as _InvoiceItem, InvoiceStatus as _InvoiceStatus, InvoiceType as _InvoiceType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async changeInvoiceStatus(arg0: bigint, arg1: InvoiceStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.changeInvoiceStatus(arg0, to_candid_InvoiceStatus_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeInvoiceStatus(arg0, to_candid_InvoiceStatus_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCustomer(arg0: Customer): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomer(arg0);
            return result;
        }
    }
    async createInventoryItem(arg0: InventoryItem): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createInventoryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInventoryItem(arg0);
            return result;
        }
    }
    async createInvoice(arg0: Invoice): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(to_candid_Invoice_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(to_candid_Invoice_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deductStock(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deductStock(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deductStock(arg0, arg1);
            return result;
        }
    }
    async deleteCustomer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return result;
        }
    }
    async deleteInventoryItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInventoryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInventoryItem(arg0);
            return result;
        }
    }
    async deleteInvoice(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInvoice(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompanySettings(): Promise<CompanySettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanySettings();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanySettings();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: bigint): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return result;
        }
    }
    async getCustomerPurchaseHistory(arg0: bigint): Promise<{
        invoiceCount: bigint;
        totalSqft: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerPurchaseHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerPurchaseHistory(arg0);
            return result;
        }
    }
    async getInventoryItem(arg0: bigint): Promise<InventoryItem> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryItem(arg0);
            return result;
        }
    }
    async getInvoice(arg0: bigint): Promise<Invoice> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_Invoice_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_Invoice_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLowStockItems(): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowStockItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowStockItems();
            return result;
        }
    }
    async getSalesSummary(): Promise<{
        totalSqft: number;
        totalInvoices: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesSummary();
            return result;
        }
    }
    async getStockReport(): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStockReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStockReport();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCustomers();
            return result;
        }
    }
    async listInventory(): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInventory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInventory();
            return result;
        }
    }
    async listInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInvoices();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInvoices();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateCompanySettings(arg0: CompanySettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCompanySettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCompanySettings(arg0);
            return result;
        }
    }
    async updateCustomer(arg0: Customer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0);
            return result;
        }
    }
    async updateInventoryItem(arg0: InventoryItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInventoryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInventoryItem(arg0);
            return result;
        }
    }
    async updateInvoice(arg0: Invoice): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvoice(to_candid_Invoice_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvoice(to_candid_Invoice_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_InvoiceItem_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceItem): InvoiceItem {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_InvoiceStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceStatus): InvoiceStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_InvoiceType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceType): InvoiceType {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Invoice_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Invoice): Invoice {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CompanySettings]): CompanySettings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _InvoiceStatus;
    deliveryAddress: _Address;
    destination: string;
    hsnSac: string;
    taxableAmount: number;
    ackDate: string;
    billingAddress: _Address;
    city: string;
    ackNumber: string;
    lrNo: string;
    igstAmount: number;
    ewayBillNo: string;
    deliveryMode: string;
    totalSqft: number;
    salesPerson: string;
    totalQty: number;
    grandTotal: number;
    invoiceDate: string;
    invoiceType: _InvoiceType;
    gstin: string;
    ratePerSqft: number;
    billNumber: string;
    irnNumber: string;
    customerId: bigint;
    gstRate: number;
    partyName: string;
    phone: string;
    items: Array<_InvoiceItem>;
    cgstAmount: number;
    sgstAmount: number;
    remarks: string;
    piNumber: string;
    vehicleNo: string;
    amountInWords: string;
    dispatchLocation: string;
    lrDate: string;
}): {
    id: bigint;
    status: InvoiceStatus;
    deliveryAddress: Address;
    destination: string;
    hsnSac: string;
    taxableAmount: number;
    ackDate: string;
    billingAddress: Address;
    city: string;
    ackNumber: string;
    lrNo: string;
    igstAmount: number;
    ewayBillNo: string;
    deliveryMode: string;
    totalSqft: number;
    salesPerson: string;
    totalQty: number;
    grandTotal: number;
    invoiceDate: string;
    invoiceType: InvoiceType;
    gstin: string;
    ratePerSqft: number;
    billNumber: string;
    irnNumber: string;
    customerId: bigint;
    gstRate: number;
    partyName: string;
    phone: string;
    items: Array<InvoiceItem>;
    cgstAmount: number;
    sgstAmount: number;
    remarks: string;
    piNumber: string;
    vehicleNo: string;
    amountInWords: string;
    dispatchLocation: string;
    lrDate: string;
} {
    return {
        id: value.id,
        status: from_candid_InvoiceStatus_n18(_uploadFile, _downloadFile, value.status),
        deliveryAddress: value.deliveryAddress,
        destination: value.destination,
        hsnSac: value.hsnSac,
        taxableAmount: value.taxableAmount,
        ackDate: value.ackDate,
        billingAddress: value.billingAddress,
        city: value.city,
        ackNumber: value.ackNumber,
        lrNo: value.lrNo,
        igstAmount: value.igstAmount,
        ewayBillNo: value.ewayBillNo,
        deliveryMode: value.deliveryMode,
        totalSqft: value.totalSqft,
        salesPerson: value.salesPerson,
        totalQty: value.totalQty,
        grandTotal: value.grandTotal,
        invoiceDate: value.invoiceDate,
        invoiceType: from_candid_InvoiceType_n20(_uploadFile, _downloadFile, value.invoiceType),
        gstin: value.gstin,
        ratePerSqft: value.ratePerSqft,
        billNumber: value.billNumber,
        irnNumber: value.irnNumber,
        customerId: value.customerId,
        gstRate: value.gstRate,
        partyName: value.partyName,
        phone: value.phone,
        items: from_candid_vec_n22(_uploadFile, _downloadFile, value.items),
        cgstAmount: value.cgstAmount,
        sgstAmount: value.sgstAmount,
        remarks: value.remarks,
        piNumber: value.piNumber,
        vehicleNo: value.vehicleNo,
        amountInWords: value.amountInWords,
        dispatchLocation: value.dispatchLocation,
        lrDate: value.lrDate
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    qty: number;
    colorCode: string;
    colorName: string;
    sqft: number;
    thickness: number;
    grade: string;
    length: number;
    batchNumber: string;
    brand: string;
    inventoryId: [] | [bigint];
    width: number;
    lineId: bigint;
}): {
    qty: number;
    colorCode: string;
    colorName: string;
    sqft: number;
    thickness: number;
    grade: string;
    length: number;
    batchNumber: string;
    brand: string;
    inventoryId?: bigint;
    width: number;
    lineId: bigint;
} {
    return {
        qty: value.qty,
        colorCode: value.colorCode,
        colorName: value.colorName,
        sqft: value.sqft,
        thickness: value.thickness,
        grade: value.grade,
        length: value.length,
        batchNumber: value.batchNumber,
        brand: value.brand,
        inventoryId: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.inventoryId)),
        width: value.width,
        lineId: value.lineId
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    saved: null;
} | {
    draft: null;
}): InvoiceStatus {
    return "saved" in value ? InvoiceStatus.saved : "draft" in value ? InvoiceStatus.draft : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    packingList: null;
} | {
    taxInvoice: null;
}): InvoiceType {
    return "packingList" in value ? InvoiceType.packingList : "taxInvoice" in value ? InvoiceType.taxInvoice : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InvoiceItem>): Array<InvoiceItem> {
    return value.map((x)=>from_candid_InvoiceItem_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Invoice>): Array<Invoice> {
    return value.map((x)=>from_candid_Invoice_n16(_uploadFile, _downloadFile, x));
}
function to_candid_InvoiceItem_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceItem): _InvoiceItem {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_InvoiceStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceStatus): _InvoiceStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_InvoiceType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceType): _InvoiceType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Invoice_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Invoice): _Invoice {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    qty: number;
    colorCode: string;
    colorName: string;
    sqft: number;
    thickness: number;
    grade: string;
    length: number;
    batchNumber: string;
    brand: string;
    inventoryId?: bigint;
    width: number;
    lineId: bigint;
}): {
    qty: number;
    colorCode: string;
    colorName: string;
    sqft: number;
    thickness: number;
    grade: string;
    length: number;
    batchNumber: string;
    brand: string;
    inventoryId: [] | [bigint];
    width: number;
    lineId: bigint;
} {
    return {
        qty: value.qty,
        colorCode: value.colorCode,
        colorName: value.colorName,
        sqft: value.sqft,
        thickness: value.thickness,
        grade: value.grade,
        length: value.length,
        batchNumber: value.batchNumber,
        brand: value.brand,
        inventoryId: value.inventoryId ? candid_some(value.inventoryId) : candid_none(),
        width: value.width,
        lineId: value.lineId
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: InvoiceStatus;
    deliveryAddress: Address;
    destination: string;
    hsnSac: string;
    taxableAmount: number;
    ackDate: string;
    billingAddress: Address;
    city: string;
    ackNumber: string;
    lrNo: string;
    igstAmount: number;
    ewayBillNo: string;
    deliveryMode: string;
    totalSqft: number;
    salesPerson: string;
    totalQty: number;
    grandTotal: number;
    invoiceDate: string;
    invoiceType: InvoiceType;
    gstin: string;
    ratePerSqft: number;
    billNumber: string;
    irnNumber: string;
    customerId: bigint;
    gstRate: number;
    partyName: string;
    phone: string;
    items: Array<InvoiceItem>;
    cgstAmount: number;
    sgstAmount: number;
    remarks: string;
    piNumber: string;
    vehicleNo: string;
    amountInWords: string;
    dispatchLocation: string;
    lrDate: string;
}): {
    id: bigint;
    status: _InvoiceStatus;
    deliveryAddress: _Address;
    destination: string;
    hsnSac: string;
    taxableAmount: number;
    ackDate: string;
    billingAddress: _Address;
    city: string;
    ackNumber: string;
    lrNo: string;
    igstAmount: number;
    ewayBillNo: string;
    deliveryMode: string;
    totalSqft: number;
    salesPerson: string;
    totalQty: number;
    grandTotal: number;
    invoiceDate: string;
    invoiceType: _InvoiceType;
    gstin: string;
    ratePerSqft: number;
    billNumber: string;
    irnNumber: string;
    customerId: bigint;
    gstRate: number;
    partyName: string;
    phone: string;
    items: Array<_InvoiceItem>;
    cgstAmount: number;
    sgstAmount: number;
    remarks: string;
    piNumber: string;
    vehicleNo: string;
    amountInWords: string;
    dispatchLocation: string;
    lrDate: string;
} {
    return {
        id: value.id,
        status: to_candid_InvoiceStatus_n3(_uploadFile, _downloadFile, value.status),
        deliveryAddress: value.deliveryAddress,
        destination: value.destination,
        hsnSac: value.hsnSac,
        taxableAmount: value.taxableAmount,
        ackDate: value.ackDate,
        billingAddress: value.billingAddress,
        city: value.city,
        ackNumber: value.ackNumber,
        lrNo: value.lrNo,
        igstAmount: value.igstAmount,
        ewayBillNo: value.ewayBillNo,
        deliveryMode: value.deliveryMode,
        totalSqft: value.totalSqft,
        salesPerson: value.salesPerson,
        totalQty: value.totalQty,
        grandTotal: value.grandTotal,
        invoiceDate: value.invoiceDate,
        invoiceType: to_candid_InvoiceType_n7(_uploadFile, _downloadFile, value.invoiceType),
        gstin: value.gstin,
        ratePerSqft: value.ratePerSqft,
        billNumber: value.billNumber,
        irnNumber: value.irnNumber,
        customerId: value.customerId,
        gstRate: value.gstRate,
        partyName: value.partyName,
        phone: value.phone,
        items: to_candid_vec_n9(_uploadFile, _downloadFile, value.items),
        cgstAmount: value.cgstAmount,
        sgstAmount: value.sgstAmount,
        remarks: value.remarks,
        piNumber: value.piNumber,
        vehicleNo: value.vehicleNo,
        amountInWords: value.amountInWords,
        dispatchLocation: value.dispatchLocation,
        lrDate: value.lrDate
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceStatus): {
    saved: null;
} | {
    draft: null;
} {
    return value == InvoiceStatus.saved ? {
        saved: null
    } : value == InvoiceStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceType): {
    packingList: null;
} | {
    taxInvoice: null;
} {
    return value == InvoiceType.packingList ? {
        packingList: null
    } : value == InvoiceType.taxInvoice ? {
        taxInvoice: null
    } : value;
}
function to_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<InvoiceItem>): Array<_InvoiceItem> {
    return value.map((x)=>to_candid_InvoiceItem_n10(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
